/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FdbApi;

public class Library {
    public static void main(String[] args) {
        System.out.println("Hello");
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
