/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Info.Drug;


public class WarningJDialog extends javax.swing.JDialog {
    private Boolean flag = false;
    /**
     * Creates new form WarningJDialog
     */
    public WarningJDialog(java.awt.Frame parent, boolean modal, Drug drug) {
        super(parent, modal);
        initComponents();
        lblInteraction.setText("There is an interaction Prescribing: " + drug.getDisplayName() + " Do you wish to continue?");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWarning = new javax.swing.JLabel();
        lblInteraction = new javax.swing.JLabel();
        jbnContinue = new javax.swing.JButton();
        jbnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(514, 85));

        lblWarning.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWarning.setText("Warning");

        lblInteraction.setText("Prescibing this will cause an interation");

        jbnContinue.setText("Continue");
        jbnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnContinueActionPerformed(evt);
            }
        });

        jbnCancel.setText("Cancel");
        jbnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInteraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jbnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(lblWarning)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInteraction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnContinue)
                    .addComponent(jbnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbnCancelActionPerformed

    private void jbnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnContinueActionPerformed
        flag = true;
        this.setVisible(false);
    }//GEN-LAST:event_jbnContinueActionPerformed
    public boolean clickedContinue(){ return flag; }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbnCancel;
    private javax.swing.JButton jbnContinue;
    private javax.swing.JLabel lblInteraction;
    private javax.swing.JLabel lblWarning;
    // End of variables declaration//GEN-END:variables
}
