/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Info.Drug;
import Info.DrugInteraction;

import java.util.List;

/**
 *
 * @author Sam
 */
public class WarningJDialog extends javax.swing.JDialog {
    private Boolean flag = false;
    /**
     * Creates new form WarningJDialog
     */
    public WarningJDialog(java.awt.Frame parent, boolean modal, Drug drug, List<DrugInteraction> interactions) {
        super(parent, modal);
        initComponents();
        StringBuilder warning = new StringBuilder("There is an interaction Prescribing: " + drug.getDisplayName());
        for (int i = 0; i < interactions.size(); i++) {
            warning.append("\n");
            warning.append(interactions.get(i).getInteractionDescription());
        }
        jtaWarn.setText(warning.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWarning = new javax.swing.JLabel();
        jbnContinue = new javax.swing.JButton();
        jbnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaWarn = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(514, 85));

        lblWarning.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWarning.setText("Warning");

        jbnContinue.setText("Continue");
        jbnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnContinueActionPerformed(evt);
            }
        });

        jbnCancel.setText("Cancel");
        jbnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnCancelActionPerformed(evt);
            }
        });

        jtaWarn.setColumns(20);
        jtaWarn.setRows(5);
        jScrollPane1.setViewportView(jtaWarn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblWarning)
                .addGap(251, 251, 251))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(jbnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnContinue)
                    .addComponent(jbnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbnCancelActionPerformed

    private void jbnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnContinueActionPerformed
        flag = true;
        this.setVisible(false);
    }//GEN-LAST:event_jbnContinueActionPerformed
    public boolean clickedContinue(){ return flag; }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnCancel;
    private javax.swing.JButton jbnContinue;
    private javax.swing.JTextArea jtaWarn;
    private javax.swing.JLabel lblWarning;
    // End of variables declaration//GEN-END:variables
}
